"""add cv review_markdown

Revision ID: 336ec217b748
Revises: aad6334bc246
Create Date: 2026-04-02 13:20:48.171173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336ec217b748'
down_revision = 'aad6334bc246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_markdown', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cvs', schema=None) as batch_op:
        batch_op.drop_column('review_markdown')

    # ### end Alembic commands ###
