"""add match score fields to cv

Revision ID: b88824a49613
Revises: cf54e70f9d9a
Create Date: 2026-06-01 13:25:32.195715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88824a49613'
down_revision = 'cf54e70f9d9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('match_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('match_summary', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('match_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('match_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('match_at')
        batch_op.drop_column('match_json')
        batch_op.drop_column('match_summary')
        batch_op.drop_column('match_score')

    # ### end Alembic commands ###
